# -*- coding: utf-8 -*-
"""Tiny Transformer Decoder Only.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TyEbr5S6m6fwtaJijsTnWGXmde47Ys1
"""

import torch
import torch.nn as nn
import math

"""
torch → PyTorch tensor operations
torch.nn → neural network layers like Linear
math → used for sqrt()
"""

class SelfAttention(nn.Module):
    def __init__(self, d_model, head_dim):
        super().__init__()

        self.Wq = nn.Linear(d_model, head_dim, bias=False)
        self.Wk = nn.Linear(d_model, head_dim, bias=False)
        self.Wv = nn.Linear(d_model, head_dim, bias=False)
    #d_model is for embedding dimension, meaning if it is 8, then every token is represented by an 8-dimensional vector.

    def forward(self,X):
      """
      X: (batch_size, seq_len, d_model)
      """
      # Q = XWq
      Q = self.Wq(X)
      # K = XWk
      K = self.Wk(X)
      # V = XWv
      V = self.Wv(X)

      """
      Input token embeddings:X transformed into: Q=XWQ K=XWK V=XWV
      """

      # Attention scores
      # (B, L, D) @ (B, D, L) -> (B, L, L)
      scores=torch.matmul(Q,K.transpose(-2,-1))

      """
      Before transpose:
      K.shape = (2,4,8)
      After:
      K.transpose(-2,-1)
      Shape:
      (2,8,4)

      (2,4,8) @ (2,8,4) = (2,4,4)

      Each entry is a dot product: q_i⋅k_j measures similarity.
      """

      #Scale
      d_k=K.size(-1)
      scores = scores / math.sqrt(d_k)

      L = scores.size(-1)
      mask = torch.triu(torch.ones(L, L, device=scores.device),diagonal=1)
      scores = scores.masked_fill(mask == 1,float('-inf'))

      #Softmax
      attention_weights=torch.softmax(scores, dim=-1)

      # Attention(Q, K, V)
      # (B, L, L) @ (B, L, D) -> (B, L, D)
      output = torch.matmul(attention_weights, V)

      """
      (2,4,4) @ (2,4,8) = (2,4,8)
      """

      return output, attention_weights

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()

        assert d_model % num_heads == 0

        head_dim = d_model // num_heads

        self.heads = nn.ModuleList([
            SelfAttention(d_model, head_dim)
            for _ in range(num_heads)
        ])

        self.proj = nn.Linear(d_model, d_model)

    def forward(self, x):

        outputs = []
        weights = []
        for head in self.heads:
          out, attn = head(x)
          outputs.append(out)
          weights.append(attn)

        out = torch.cat(outputs, dim=-1)

        out = self.proj(out)

        return out,weights

class FeedForward(nn.Module):
    def __init__(self, d_model, hidden_dim):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(d_model, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, d_model)
        )

    def forward(self, x):
        return self.net(x)

class TransformerBlock(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()

        self.attn = MultiHeadAttention(d_model, num_heads)

        self.ffn = FeedForward(
            d_model,
            hidden_dim=4 * d_model
        )

        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)

    def forward(self, x):

        # attention sublayer
        attn_out, attn_weights = self.attn(x)
        x = self.norm1(
            x + attn_out
        )

        # feed-forward sublayer
        x = self.norm2(
            x + self.ffn(x)
        )

        return x

class PositionalEmbedding(nn.Module):
    def __init__(self, max_len, d_model):
        super().__init__()

        self.embedding = nn.Embedding(
            max_len,
            d_model
        )

    def forward(self, seq_len):

        positions = torch.arange(seq_len,device=self.embedding.weight.device)

        return self.embedding(positions)

class TransformerDecoder(nn.Module):
    def __init__(
        self,
        vocab_size,
        d_model=128,
        num_heads=4,
        num_layers=4,
        max_len=512
    ):
        super().__init__()

        self.token_embedding = nn.Embedding(
            vocab_size,
            d_model
        )

        self.position_embedding = PositionalEmbedding(
            max_len,
            d_model
        )

        self.layers = nn.ModuleList([
            TransformerBlock(
                d_model,
                num_heads
            )
            for _ in range(num_layers)
        ])

    def forward(self, tokens):
        """
        tokens: (batch, seq_len)
        """

        B, T = tokens.shape

        tok_emb = self.token_embedding(tokens)

        pos_emb = self.position_embedding(T)

        x = tok_emb + pos_emb

        for layer in self.layers:
            x = layer(x)

        return x

class TransformerLM(nn.Module):
    def __init__(
        self,
        vocab_size,
        d_model=128,
        num_heads=4,
        num_layers=4
    ):
        super().__init__()

        self.decoder = TransformerDecoder(
            vocab_size,
            d_model,
            num_heads,
            num_layers
        )

        self.lm_head = nn.Linear(
            d_model,
            vocab_size
        )

    def forward(self, tokens):

        x = self.decoder(tokens)

        logits = self.lm_head(x)

        return logits

if __name__ == "__main__":
  vocab_size = 1000
  x = torch.randint(0, vocab_size, (2, 16))
  model = TransformerLM(vocab_size)
  logits = model(x)
  print(logits.shape)